import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App.jsx";
import "./styles.css";
import "./login.css";
import "./system.css";
import "./desktop-tools.css";
import "./creative.css";
import "./photo-experience.css";
createRoot(document.getElementById("root")).render(<App />);
